stages:
  preprocessing:
    cmd: python -m src.preprocessing
    frozen: false
    deps:
      - src/preprocessing.py
      - src/common/utils.py

      # - data/processed/exclude.txt

      - /home/cjber/data/places-2023_04_11.parquet
      - /home/cjber/data/places_full-2023_04_11.parquet
      - /home/cjber/data/en_regions.parquet
    outs:
      - data/processed/place_regions.parquet
      - data/processed/places.parquet
  embeddings:
    cmd: python -m src.embeddings
    frozen: false
    deps:
      - src/embeddings.py
      - src/common/utils.py

      # - data/processed/exclude.txt
      - data/processed/places.parquet
    outs:
      - data/processed/region_embeddings.parquet
  zero_shot:
    cmd: python -m src.zero_shot
    frozen: true
    deps:
      - src/zero_shot.py
      - src/common/utils.py

      # - data/processed/exclude.txt
      - data/processed/places.parquet
    outs:
      - data/processed/places_zero_shot.parquet
  paper:
    cmd: quarto render paper/main.qmd --execute-dir=$PWD
    frozen: false
    deps:
      - paper/figures
      - paper/main.qmd

      - data/processed
    outs:
      - paper/main.pdf
